### ISSUE TITLE
Could not initialize class org.jacoco.core.internal.flow.ClassProbesAdapter

### ISSUE THREAD

**Issue by calvarez-ov** [jacoco/jacoco#639]
JaCoCo version: 0.8.0
Operating system: Linux
Tool integration: Android gradle

I'm running into an issue in an android project, after updating from jacoco 0.7.9 to 0.8.0.
Not sure if this should be reported here, or somewhere else... Starting here since it works fine with 0.7.9.

When running `./gradlew clean assembleDebug`:
### Expected behaviour
The command completes without error, producing an apk.

### Actual behaviour
I get the below exception:
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jacoco.core.internal.flow.ClassProbesAdapter
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:88)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:108)
        at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:135)
        at com.android.build.gradle.internal.transforms.JacocoTransform.instrumentFile(JacocoTransform.java:172)
        at com.android.build.gradle.internal.transforms.JacocoTransform.instrumentFilesFullRun(JacocoTransform.java:160)
        at com.android.build.gradle.internal.transforms.JacocoTransform.transform(JacocoTransform.java:119)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:185)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:181)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:176)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:179)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:135)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:122)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)

```

I should note that I have updated two other android projects to use jacoco 0.8.0, and they seem to work fine. I haven't yet identified what's different in this project.

I've integrated jacoco as follows:

root `build.gradle` file:
```gradle
buildscript {
     dependencies {
         classpath 'com.android.tools.build:gradle:3.0.1'
         classpath 'org.jacoco:org.jacoco.core:0.8.0'
    }
}
```

app module `build.gradle` file:
```gradle
apply plugin: 'jacoco'
android {
    buildTypes {
        debug {
            testCoverageEnabled = true
        }
    }
    testOptions {
        unitTests {
            all {
                jacoco {
                    // We need to set includeNoLocationClasses or robolectric tests won't be counted:
                    // https://stackoverflow.com/questions/35735085/jacoco-doesnt-work-with-robolectric-tests
                    includeNoLocationClasses = true
                }
        }
    }
}
jacoco {
    toolVersion '0.8.0'
}
/** other config for configuring the jaoco report, but I think it's irrelevant for this bug which occurs earlier, in `assembleDebug` **/
```

I've found a workaround for now:
* set `testCoverageEnabled = false` by default
* when running unit tests (`testDebugUnitTest`), then set `testCoverageEnabled = true`

(I've done this with a property instead of manually changing the `build.gradle` each time, but omitted that here.)

**Comment by calvarez-ov** [comment]
Note: I don't see the issue in a plain java (not-android) gradle project. Jacoco 0.8.0 works fine there even if the project includes the fabric dependency.

So it looks like an issue with the specific combination of android + fabric + jacoco.

**Comment by Godin** [comment]
@calvarez-ov according to command `gradle buildEnvironment` on
```
buildscript {
  repositories {
    google()
    jcenter()
    maven { url 'https://maven.fabric.io/public' }
  }
  dependencies {
    classpath 'io.fabric.tools:gradle:1.+'
  }
}
```
dependency `io.fabric.tools:gradle:1.+` resolves into version `1.25.1`. Its JAR file (https://maven.fabric.io/public/io/fabric/tools/gradle/1.25.1/gradle-1.25.1.jar) contains copy of classes of ASM library. In this copy there is no constant `ASM6` in `org/objectweb/asm/Opcodes.class`, so this is a copy of some ASM 5.x version.

However JaCoCo 0.8.0 requires ASM 6.0 and `org.jacoco:org.jacoco.core:0.8.0` correctly declares dependencies on ASM. An attempt to use `org.jacoco.core.instr.Instrumenter` from JaCoCo 0.8.0 for example with ASM 5.2 correctly and expectedly results in
```
java.lang.ExceptionInInitializerError
	at org.jacoco.core.instr.Instrumenter.instrument(Instrumenter.java:88)
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.MethodVisitor.<init>(MethodVisitor.java:93)
	at org.jacoco.core.internal.flow.MethodProbesVisitor.<init>(MethodProbesVisitor.java:39)
	at org.jacoco.core.internal.flow.MethodProbesVisitor.<init>(MethodProbesVisitor.java:29)
	at org.jacoco.core.internal.flow.ClassProbesAdapter$1.<init>(ClassProbesAdapter.java:26)
	at org.jacoco.core.internal.flow.ClassProbesAdapter.<clinit>(ClassProbesAdapter.java:26)
```
which later can lead to
```
java.lang.NoClassDefFoundError: Could not initialize class org.jacoco.core.internal.flow.ClassProbesAdapter
```

Execution of
```
task printBuildScriptClasspath << {
  println project.buildscript.configurations.classpath.asPath
}
```
in case of
```
buildscript {
  dependencies {
    classpath 'com.android.tools.build:gradle:3.0.1'
    classpath 'io.fabric.tools:gradle:1.+'
  }
}
```
shows that JAR of `io.fabric.tools:gradle` comes before ASM JARs. Most likely `com.android.build.gradle.internal.transforms.JacocoTransform` doesn't isolate execution of `org.jacoco.core.instr.Instrumenter` via dedicated classloader so that most likely it is affected by a copy of ASM in `io.fabric.tools:gradle`. 

`org.jacoco.core` has been designed to have and from the beginning has ASM as a dependency and I personally don't see reasons to change this (@marchof ?). You can ask developers of `com.android.tools.build:gradle` about isolation and/or better integration of JaCoCo library (CC @allenhair); or/and ask developers of `io.fabric.tools:gradle` about removal/relocation of ASM copy or about declaration of dependency instead of copy.

Wild guess of possible workaround assuming that buildscript classpath entries form ordered list in Gradle (that `println project.buildscript.configurations.classpath.asPath` shows) based on order of entries: @calvarez-ov could you please try to declare `org.ow2.asm:asm:6.0` before `io.fabric.tools:gradle:1.+` i.e. as
```
buildscript {
  dependencies {
    classpath 'org.ow2.asm:asm:6.0'
    classpath 'org.jacoco:org.jacoco.core:0.8.0'
    classpath 'com.android.tools.build:gradle:3.0.1'
    classpath 'io.fabric.tools:gradle:1.+'
  }
}
```
?

**Comment by allenhair** [comment]
@calvarez-ov You can file this to the Android issue tracker by following the steps at https://developer.android.com/studio/report-bugs.html. Be sure to provide the information listed under the ["Details for build tools and Gradle bugs"](https://developer.android.com/studio/report-bugs.html#build-bugs) section.

**Comment by calvarez-ov** [comment]
@Godin Indeed, declaring the buildscript dependencies in this order (asm, jacoco, fabric) removed the error. Thanks!

**Comment by calvarez-ov** [comment]
@allenhair I'd be happy to submit an issue to the Android issue tracker, but actually I'm not sure what the problem is in the android build tools.  

I could understand opening a fabric issue though.  I could request for them to either declare a dependency on a later version of asm (instead of including a copy), or to relocate the asm classes if they really need that older asm version for some reason.

**Comment by calvarez-ov** [comment]
I've contacted fabric support. I have no ticket number to share here as the only way I could find to report an issue was to send an email to support@fabric.io :)

**Comment by Godin** [comment]
@allenhair hope that summon did not bother you, and thanks for showing up here ❤️ 

@calvarez-ov glad that workaround works 😌  😋  thanks for confirmation and email to Fabric 👍 

For the record as another possible workaround: maybe there is a way to use JaCoCo 0.7.9 for instrumentation and hence to produce exec-file (with all negative consequences such as #626), while use JaCoCo 0.8.0 for consumption of exec-file and generation of report (with all positive consequences such as filtering) since exec-file format is compatible.

Maybe I'll find some time in future to dump thoughts about this problem and possible improvements into Android issue tracker.

**Comment by MathiasSeguy-Android2EE** [comment]
@Godin Thank you for the workaround and the so clear answer.

**Comment by usamakzafar** [comment]
@Godin Thank you!
